// Full tool catalog for devtoolshub
window.CATEGORIES = [
  { slug: "json",        name: "JSON",        glyph: "{ }", color: "oklch(0.82 0.14 95)",  description: "Parse, format, validate and convert JSON — the lingua franca of APIs." },
  { slug: "text",        name: "Text",        glyph: "Aa",  color: "oklch(0.84 0.09 200)", description: "Manipulate, transform, count and clean any text." },
  { slug: "markdown",    name: "Markdown",    glyph: "M↓",  color: "oklch(0.83 0.11 60)",  description: "Preview, convert and format Markdown for docs and READMEs." },
  { slug: "encoding",    name: "Encoding",    glyph: "01",  color: "oklch(0.82 0.12 320)", description: "Base64, URL, HTML, JWT, hash — encode and decode everything." },
  { slug: "converters",  name: "Converters",  glyph: "⇄",   color: "oklch(0.83 0.10 150)", description: "CSV, YAML, XML, TOML — move between data formats losslessly." },
  { slug: "formatters",  name: "Formatters",  glyph: "{ }", color: "oklch(0.82 0.10 25)",  description: "Pretty-print and minify HTML, CSS, JS, SQL, XML." },
  { slug: "web",         name: "Web",         glyph: "</>", color: "oklch(0.82 0.11 260)", description: "HTTP status codes, MIME types, headers, User-Agent parser." },
  { slug: "color",       name: "Color",       glyph: "◐",   color: "oklch(0.82 0.14 15)",  description: "Convert colors, build palettes, check contrast." },
  { slug: "time",        name: "Time & Date", glyph: "⏱",   color: "oklch(0.82 0.10 100)", description: "Timestamps, timezones, cron, durations." },
  { slug: "images",      name: "Images",      glyph: "▣",   color: "oklch(0.82 0.12 170)", description: "Resize, compress, convert and inspect images locally." },
  { slug: "regex",       name: "Regex",       glyph: "/./",  color: "oklch(0.82 0.14 340)", description: "Test, build and explain regular expressions." },
  { slug: "utilities",   name: "Utilities",   glyph: "⌘",   color: "oklch(0.83 0.09 270)", description: "UUIDs, lorem ipsum, diff, random — the kitchen sink." },
];

// Each tool: slug, category, name, desc, popular?, live? (has real working demo)
const T = (category) => (slug, name, desc, opts = {}) => ({ category, slug, name, desc, ...opts });

window.TOOLS = [
  // ── JSON ──
  ...[
    T("json")("json-formatter", "JSON Formatter", "Pretty-print, validate and minify JSON with syntax highlighting.", { popular: true, live: true }),
    T("json")("json-validator", "JSON Validator", "Validate JSON against RFC 8259 with precise error locations.", { live: true }),
    T("json")("json-to-csv", "JSON to CSV", "Convert arrays of objects into clean CSV.", { popular: true, live: true }),
    T("json")("csv-to-json", "CSV to JSON", "Parse CSV into structured JSON arrays.", { live: true }),
    T("json")("json-to-yaml", "JSON to YAML", "Bidirectional JSON ↔ YAML conversion.", { live: true }),
    T("json")("json-to-xml", "JSON to XML", "Convert between JSON and XML trees.", { live: true }),
    T("json")("json-to-table", "JSON to Table", "Render JSON as a sortable HTML table.", { popular: true, live: true }),
    T("json")("json-minifier", "JSON Minifier", "Strip whitespace for the smallest payload.", { live: true }),
    T("json")("json-diff", "JSON Diff", "Compare two JSON documents structurally.", { live: true }),
    T("json")("jsonpath-tester", "JSONPath Tester", "Run JSONPath queries interactively.", { live: true }),
    T("json")("json-schema-validator", "Schema Validator", "Validate JSON against a JSON Schema.", { live: true }),
    T("json")("json-escape", "JSON Escape", "Escape strings for embedding in JSON.", { live: true }),
    T("json")("json-sort-keys", "Sort JSON Keys", "Alphabetise object keys recursively.", { live: true }),
    T("json")("json-to-typescript", "JSON to TypeScript", "Generate TS interfaces from a JSON sample.", { live: true }),
    T("json")("json-to-go-struct", "JSON to Go Struct", "Generate idiomatic Go structs from JSON.", { live: true }),
    T("json")("json-flattener", "JSON Flattener", "Flatten nested JSON to dot-notation keys.", { live: true }),
    T("json")("json-query", "JSON Query", "Run jq-style queries in the browser.", { live: true }),
  ],
  // ── Text ──
  ...[
    T("text")("case-converter", "Case Converter", "camelCase, snake_case, PascalCase, kebab-case, CONSTANT_CASE.", { popular: true, live: true }),
    T("text")("word-counter", "Word Counter", "Count words, characters, sentences, reading time.", { live: true }),
    T("text")("line-sorter", "Line Sorter", "Sort, reverse, dedupe and shuffle lines.", { live: true }),
    T("text")("remove-duplicates", "Remove Duplicates", "Dedupe lines with one click.", { live: true }),
    T("text")("text-diff", "Text Diff", "Side-by-side character and word diff.", { popular: true, live: true }),
    T("text")("lorem-ipsum", "Lorem Ipsum", "Classic or custom placeholder text.", { live: true }),
    T("text")("find-replace", "Find & Replace", "Regex-powered find and replace.", { live: true }),
    T("text")("slugify", "Slugify", "URL-safe slugs from any string.", { live: true }),
    T("text")("whitespace-cleaner", "Whitespace Cleaner", "Trim, collapse and normalise whitespace.", { live: true }),
    T("text")("reverse-text", "Reverse Text", "Reverse characters, words or lines.", { live: true }),
    T("text")("text-repeater", "Text Repeater", "Repeat any string n times.", { live: true }),
    T("text")("count-occurrences", "Count Occurrences", "Count instances of a substring or pattern.", { live: true }),
    T("text")("text-to-binary", "Text to Binary", "Encode any string to binary and back.", { live: true }),
    T("text")("unicode-inspector", "Unicode Inspector", "See every codepoint, category and name.", { live: true }),
    T("text")("zalgo-generator", "Zalgo Text", "Corrupt text with combining marks.", { live: true }),
    T("text")("fancy-text", "Fancy Text", "Unicode styled text: bold, italic, script.", { live: true }),
  ],
  // ── Markdown ──
  ...[
    T("markdown")("markdown-preview", "Markdown Preview", "Live-rendered GFM preview.", { popular: true, live: true }),
    T("markdown")("markdown-to-html", "Markdown to HTML", "Convert MD to clean semantic HTML.", { live: true }),
    T("markdown")("html-to-markdown", "HTML to Markdown", "Clean HTML → readable Markdown.", { live: true }),
    T("markdown")("markdown-to-excel", "Markdown to Excel", "Convert MD tables to CSV (open in Excel).", { live: true }),
    T("markdown")("markdown-table-generator", "Table Generator", "Build Markdown tables visually.", { live: true }),
    T("markdown")("readme-generator", "README Generator", "Template-driven README.md generator.", { live: true }),
    T("markdown")("mdx-linter", "MDX Linter", "Lint MDX for common issues.", { live: true }),
    T("markdown")("toc-generator", "Table of Contents", "Auto-generate a TOC from headings.", { live: true }),
    T("markdown")("github-emoji", "GitHub Emoji", "Search & copy GitHub-flavoured emoji shortcodes.", { live: true }),
  ],
  // ── Encoding ──
  ...[
    T("encoding")("base64-encode", "Base64 Encode/Decode", "Encode or decode Base64, with URL-safe option.", { popular: true, live: true }),
    T("encoding")("url-encode", "URL Encode/Decode", "Percent-encode or decode URIs.", { popular: true, live: true }),
    T("encoding")("jwt-decoder", "JWT Decoder", "Inspect header, payload and signature of any JWT.", { popular: true, live: true }),
    T("encoding")("html-entities", "HTML Entities", "Escape or unescape HTML entities.", { live: true }),
    T("encoding")("md5-hash", "MD5 Hash", "Compute MD5 of any string.", { live: true }),
    T("encoding")("sha256-hash", "SHA-256 Hash", "Compute SHA-256 digests.", { live: true }),
    T("encoding")("sha1-hash", "SHA-1 Hash", "Compute SHA-1 digests.", { live: true }),
    T("encoding")("sha512-hash", "SHA-512 Hash", "Compute SHA-512 digests.", { live: true }),
    T("encoding")("hex-encoder", "Hex Encoder", "Text ↔ hex conversion.", { live: true }),
    T("encoding")("binary-encoder", "Binary Encoder", "Text ↔ binary conversion.", { live: true }),
    T("encoding")("rot13", "ROT13", "The classic Caesar cipher.", { live: true }),
    T("encoding")("morse-code", "Morse Code", "Text ↔ morse code translator.", { live: true }),
    T("encoding")("basic-auth-generator", "Basic Auth Header", "Generate Authorization: Basic headers.", { live: true }),
    T("encoding")("bcrypt-hash", "Bcrypt Hash", "Hash a password with bcrypt.", { live: true }),
  ],
  // ── Converters ──
  ...[
    T("converters")("yaml-to-json", "YAML to JSON", "YAML ↔ JSON with key preservation.", { live: true }),
    T("converters")("xml-to-json", "XML to JSON", "Convert XML trees to JSON.", { live: true }),
    T("converters")("toml-to-json", "TOML to JSON", "Modern config format conversion.", { live: true }),
    T("converters")("sql-to-json", "SQL Insert to JSON", "Parse INSERT statements into objects.", { live: true }),
    T("converters")("curl-to-fetch", "cURL to fetch()", "Convert cURL commands to JavaScript fetch.", { popular: true, live: true }),
    T("converters")("curl-to-code", "cURL to Code", "cURL → Python, Go, Node, PHP, Rust.", { live: true }),
    T("converters")("number-base", "Number Base Converter", "Bin, oct, dec, hex — any base.", { live: true }),
    T("converters")("unit-converter", "Unit Converter", "Length, weight, temperature, data sizes.", { live: true }),
    T("converters")("byte-size", "Byte Size Converter", "Human ↔ bytes (KB, MiB, GB, etc.).", { live: true }),
    T("converters")("css-units", "CSS Units", "px, rem, em, pt, %, vw, vh.", { live: true }),
  ],
  // ── Formatters ──
  ...[
    T("formatters")("html-formatter", "HTML Formatter", "Pretty-print HTML with configurable indent.", { live: true }),
    T("formatters")("css-formatter", "CSS Formatter", "Format and sort CSS declarations.", { live: true }),
    T("formatters")("js-formatter", "JavaScript Formatter", "Prettier-powered JS formatting.", { live: true }),
    T("formatters")("ts-formatter", "TypeScript Formatter", "Format TS with your preferred rules.", { live: true }),
    T("formatters")("sql-formatter", "SQL Formatter", "Readable SQL with dialect awareness.", { live: true }),
    T("formatters")("xml-formatter", "XML Formatter", "Pretty-print or minify XML.", { live: true }),
    T("formatters")("graphql-formatter", "GraphQL Formatter", "Format queries and schemas.", { live: true }),
    T("formatters")("go-formatter", "Go Formatter", "Brace-based indenter.", { live: true }),
    T("formatters")("python-formatter", "Python Formatter", "Indent-normalizing Python formatter.", { live: true }),
  ],
  // ── Web ──
  ...[
    T("web")("http-status", "HTTP Status Codes", "Search all HTTP status codes with examples.", { popular: true }),
    T("web")("mime-types", "MIME Type Lookup", "Find MIME types by extension or name."),
    T("web")("user-agent-parser", "User-Agent Parser", "Parse any User-Agent string."),
    T("web")("url-parser", "URL Parser", "Break a URL into its components."),
    T("web")("ip-lookup", "IP Address Info", "Inspect IPv4/IPv6 addresses."),
    T("web")("dns-lookup", "DNS Lookup", "A, AAAA, MX, TXT, CNAME."),
    T("web")("cors-tester", "CORS Tester", "Preflight any endpoint from the browser."),
    T("web")("headers-analyzer", "Headers Analyzer", "Check security headers of any URL."),
    T("web")("robots-tester", "robots.txt Tester", "Validate a robots.txt file."),
    T("web")("htaccess-tester", ".htaccess Tester", "Simulate Apache redirects."),
  ],
  // ── Color ──
  ...[
    T("color")("color-picker", "Color Picker", "Pick a color, get every format.", { popular: true, live: true }),
    T("color")("color-converter", "Color Converter", "HEX ↔ RGB ↔ HSL ↔ OKLCH.", { live: true }),
    T("color")("contrast-checker", "Contrast Checker", "WCAG AA/AAA contrast verifier.", { live: true }),
    T("color")("palette-generator", "Palette Generator", "Build harmonised color palettes."),
    T("color")("gradient-generator", "Gradient Generator", "Visual gradient editor with CSS output."),
    T("color")("color-blindness", "Color Blindness Sim", "Preview designs under 8 deficiencies."),
    T("color")("tailwind-color-finder", "Tailwind Color Finder", "Find the closest Tailwind palette entry."),
  ],
  // ── Time ──
  ...[
    T("time")("timestamp-converter", "Timestamp Converter", "Unix ↔ ISO 8601 ↔ human dates.", { popular: true, live: true }),
    T("time")("timezone-converter", "Timezone Converter", "Convert times across zones."),
    T("time")("cron-parser", "Cron Parser", "Explain and preview cron expressions."),
    T("time")("cron-builder", "Cron Builder", "Build cron expressions with a UI."),
    T("time")("duration-calculator", "Duration Calculator", "Add, subtract and diff times."),
    T("time")("date-formatter", "Date Formatter", "Format dates with strftime, moment or Intl tokens."),
    T("time")("age-calculator", "Age Calculator", "Exact age in years, days, seconds."),
    T("time")("week-number", "Week Number", "ISO week numbers for any date."),
  ],
  // ── Images ──
  ...[
    T("images")("image-compressor", "Image Compressor", "Lossy/lossless compression in-browser."),
    T("images")("image-resizer", "Image Resizer", "Resize with exact dims or percentage."),
    T("images")("image-to-base64", "Image to Base64", "Embed images as data URIs."),
    T("images")("webp-converter", "WebP Converter", "PNG/JPG ↔ WebP."),
    T("images")("svg-optimizer", "SVG Optimizer", "Shrink SVG via SVGO in-browser."),
    T("images")("favicon-generator", "Favicon Generator", "All favicon sizes from one image."),
    T("images")("exif-viewer", "EXIF Viewer", "Inspect & strip EXIF metadata."),
    T("images")("qr-generator", "QR Code Generator", "Generate QR codes from any string.", { popular: true, live: true }),
    T("images")("barcode-generator", "Barcode Generator", "Code 128, EAN-13, UPC."),
  ],
  // ── Regex ──
  ...[
    T("regex")("regex-tester", "Regex Tester", "Test and explain regular expressions.", { popular: true, live: true }),
    T("regex")("regex-cheatsheet", "Regex Cheatsheet", "Every metacharacter, at a glance."),
    T("regex")("regex-builder", "Regex Builder", "Build regex from a visual UI."),
    T("regex")("regex-library", "Regex Library", "Copy-paste common patterns."),
    T("regex")("regex-replace", "Regex Replace", "Find & replace with capture groups."),
  ],
  // ── Utilities ──
  ...[
    T("utilities")("uuid-generator", "UUID Generator", "Generate v1/v4/v7 UUIDs in bulk.", { popular: true, live: true }),
    T("utilities")("nanoid-generator", "Nano ID Generator", "Tiny URL-safe random IDs.", { live: true }),
    T("utilities")("password-generator", "Password Generator", "Strong passwords with entropy meter.", { live: true }),
    T("utilities")("random-number", "Random Number", "Secure random numbers, ranges, picks."),
    T("utilities")("random-picker", "Random Picker", "Pick random items from a list."),
    T("utilities")("diff-checker", "Diff Checker", "Side-by-side file diff."),
    T("utilities")("lorem-pixel", "Placeholder Images", "Generate placeholder image URLs."),
    T("utilities")("checksum-verifier", "Checksum Verifier", "Verify file integrity against a hash."),
    T("utilities")("keycode-info", "Keycode Info", "Press any key, see its codes."),
    T("utilities")("mock-data", "Mock Data Generator", "Fake names, emails, addresses, numbers."),
  ],
];
